export type ArticleInfo = {
  id: string;
  title: string;
  subtitle: string;
  author: string;
  publication_id: string;
  published_at: Date;
  last_modified_at: Date;
  tags: string[];
  topics: string[];
  claps: number;
  voters: number;
  word_count: number;
  responses_count: number;
  reading_time: number;
  url: string;
  unique_slug: string;
  image_url: string;
  lang: string;
  is_series: boolean;
  is_locked: boolean;
  is_shortform: boolean;
  top_highlight: string;
};
